// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bifrost/receivedTxs.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReceivedTxs struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id             uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Txid           string `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	TezosSender    string `protobuf:"bytes,4,opt,name=tezosSender,proto3" json:"tezosSender,omitempty"`
	CosmosReceiver string `protobuf:"bytes,5,opt,name=cosmosReceiver,proto3" json:"cosmosReceiver,omitempty"`
	Amount         string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom          string `protobuf:"bytes,7,opt,name=denom,proto3" json:"denom,omitempty"`
	SrcChain       string `protobuf:"bytes,8,opt,name=srcChain,proto3" json:"srcChain,omitempty"`
	DestChain      string `protobuf:"bytes,9,opt,name=destChain,proto3" json:"destChain,omitempty"`
	TxStatus       string `protobuf:"bytes,10,opt,name=txStatus,proto3" json:"txStatus,omitempty"`
	Timestamp      string `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RelayTimestamp string `protobuf:"bytes,12,opt,name=relayTimestamp,proto3" json:"relayTimestamp,omitempty"`
}

func (m *ReceivedTxs) Reset()         { *m = ReceivedTxs{} }
func (m *ReceivedTxs) String() string { return proto.CompactTextString(m) }
func (*ReceivedTxs) ProtoMessage()    {}
func (*ReceivedTxs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8899200e1efad237, []int{0}
}
func (m *ReceivedTxs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReceivedTxs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReceivedTxs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReceivedTxs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivedTxs.Merge(m, src)
}
func (m *ReceivedTxs) XXX_Size() int {
	return m.Size()
}
func (m *ReceivedTxs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivedTxs.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivedTxs proto.InternalMessageInfo

func (m *ReceivedTxs) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ReceivedTxs) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReceivedTxs) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ReceivedTxs) GetTezosSender() string {
	if m != nil {
		return m.TezosSender
	}
	return ""
}

func (m *ReceivedTxs) GetCosmosReceiver() string {
	if m != nil {
		return m.CosmosReceiver
	}
	return ""
}

func (m *ReceivedTxs) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ReceivedTxs) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *ReceivedTxs) GetSrcChain() string {
	if m != nil {
		return m.SrcChain
	}
	return ""
}

func (m *ReceivedTxs) GetDestChain() string {
	if m != nil {
		return m.DestChain
	}
	return ""
}

func (m *ReceivedTxs) GetTxStatus() string {
	if m != nil {
		return m.TxStatus
	}
	return ""
}

func (m *ReceivedTxs) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ReceivedTxs) GetRelayTimestamp() string {
	if m != nil {
		return m.RelayTimestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*ReceivedTxs)(nil), "sap200.bifrost.bifrost.ReceivedTxs")
}

func init() { proto.RegisterFile("bifrost/receivedTxs.proto", fileDescriptor_8899200e1efad237) }

var fileDescriptor_8899200e1efad237 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x69, 0xe5, 0x77, 0x30, 0x2c, 0x26, 0x84, 0x8c, 0xc4, 0x34, 0xc4, 0x85, 0xc1, 0x0d,
	0x25, 0xfa, 0x06, 0xf2, 0x06, 0xc0, 0xca, 0xdd, 0xd0, 0x19, 0x61, 0x12, 0xa7, 0xb7, 0x99, 0xb9,
	0x98, 0xe2, 0x53, 0xf8, 0x58, 0x2e, 0x59, 0xba, 0xd3, 0xc0, 0x8b, 0x98, 0xce, 0xd0, 0xa2, 0xae,
	0x7a, 0xcf, 0x39, 0xdf, 0xe9, 0xe4, 0xe6, 0x92, 0xab, 0x95, 0x7a, 0x36, 0x60, 0x31, 0x36, 0x32,
	0x91, 0xea, 0x55, 0x8a, 0x65, 0x6e, 0x27, 0x99, 0x01, 0x04, 0x3a, 0xb0, 0x3c, 0xbb, 0x9f, 0x4e,
	0x27, 0x27, 0xa2, 0xfc, 0x0e, 0xfb, 0x6b, 0x58, 0x83, 0x43, 0xe2, 0x62, 0xf2, 0xf4, 0xcd, 0x57,
	0x48, 0xba, 0xf3, 0xf3, 0x3f, 0x28, 0x23, 0xad, 0xc4, 0x48, 0x8e, 0x60, 0x58, 0x30, 0x0a, 0xc6,
	0x9d, 0x79, 0x29, 0x69, 0x8f, 0x84, 0x4a, 0xb0, 0x70, 0x14, 0x8c, 0xeb, 0xf3, 0x50, 0x09, 0x4a,
	0x49, 0x1d, 0x73, 0x25, 0xd8, 0x85, 0xc3, 0xdc, 0x4c, 0x47, 0xa4, 0x8b, 0xf2, 0x0d, 0xec, 0x42,
	0xa6, 0x42, 0x1a, 0x56, 0x77, 0xd1, 0x6f, 0x8b, 0xde, 0x92, 0x5e, 0x02, 0x56, 0x83, 0x3d, 0x3d,
	0x6a, 0x58, 0xc3, 0x41, 0xff, 0x5c, 0x3a, 0x20, 0x4d, 0xae, 0x61, 0x9b, 0x22, 0x6b, 0xba, 0xfc,
	0xa4, 0x68, 0x9f, 0x34, 0x84, 0x4c, 0x41, 0xb3, 0x96, 0xb3, 0xbd, 0xa0, 0x43, 0xd2, 0xb6, 0x26,
	0x99, 0x6d, 0xb8, 0x4a, 0x59, 0xdb, 0x05, 0x95, 0xa6, 0xd7, 0xa4, 0x23, 0xa4, 0x45, 0x1f, 0x76,
	0x5c, 0x78, 0x36, 0x8a, 0x26, 0xe6, 0x0b, 0xe4, 0xb8, 0xb5, 0x8c, 0xf8, 0x66, 0xa9, 0x8b, 0x26,
	0x2a, 0x2d, 0x2d, 0x72, 0x9d, 0xb1, 0xae, 0x6f, 0x56, 0x46, 0xb1, 0x89, 0x91, 0x2f, 0x7c, 0xb7,
	0xac, 0x90, 0x4b, 0xbf, 0xc9, 0x5f, 0xf7, 0x71, 0xf6, 0x71, 0x88, 0x82, 0xfd, 0x21, 0x0a, 0xbe,
	0x0f, 0x51, 0xf0, 0x7e, 0x8c, 0x6a, 0xfb, 0x63, 0x54, 0xfb, 0x3c, 0x46, 0xb5, 0xa7, 0xbb, 0xb5,
	0xc2, 0xcd, 0x76, 0x35, 0x49, 0x40, 0xc7, 0xfe, 0x68, 0x71, 0x79, 0xd6, 0xbc, 0x9a, 0x70, 0x97,
	0x49, 0xbb, 0x6a, 0xba, 0x6b, 0x3d, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x4d, 0x80, 0x52,
	0xf8, 0x01, 0x00, 0x00,
}

func (m *ReceivedTxs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReceivedTxs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReceivedTxs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayTimestamp) > 0 {
		i -= len(m.RelayTimestamp)
		copy(dAtA[i:], m.RelayTimestamp)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.RelayTimestamp)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.TxStatus) > 0 {
		i -= len(m.TxStatus)
		copy(dAtA[i:], m.TxStatus)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.TxStatus)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.DestChain) > 0 {
		i -= len(m.DestChain)
		copy(dAtA[i:], m.DestChain)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.DestChain)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.SrcChain) > 0 {
		i -= len(m.SrcChain)
		copy(dAtA[i:], m.SrcChain)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.SrcChain)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CosmosReceiver) > 0 {
		i -= len(m.CosmosReceiver)
		copy(dAtA[i:], m.CosmosReceiver)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.CosmosReceiver)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TezosSender) > 0 {
		i -= len(m.TezosSender)
		copy(dAtA[i:], m.TezosSender)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.TezosSender)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Txid) > 0 {
		i -= len(m.Txid)
		copy(dAtA[i:], m.Txid)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.Txid)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintReceivedTxs(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintReceivedTxs(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintReceivedTxs(dAtA []byte, offset int, v uint64) int {
	offset -= sovReceivedTxs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReceivedTxs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovReceivedTxs(uint64(m.Id))
	}
	l = len(m.Txid)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.TezosSender)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.CosmosReceiver)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.SrcChain)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.DestChain)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.TxStatus)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	l = len(m.RelayTimestamp)
	if l > 0 {
		n += 1 + l + sovReceivedTxs(uint64(l))
	}
	return n
}

func sovReceivedTxs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReceivedTxs(x uint64) (n int) {
	return sovReceivedTxs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReceivedTxs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReceivedTxs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReceivedTxs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReceivedTxs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TezosSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TezosSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelayTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReceivedTxs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReceivedTxs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReceivedTxs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReceivedTxs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReceivedTxs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReceivedTxs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReceivedTxs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReceivedTxs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReceivedTxs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReceivedTxs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReceivedTxs = fmt.Errorf("proto: unexpected end of group")
)
